// Generated by `scripts/build_typify_input.py` + `cargo typify`.
// Do not edit `components.rs` or `tags.rs` by hand — re-run
// `scripts/regenerate-types.sh` after changing the snapshot or an override.
//
// `components` holds every type in the eToro OpenAPI component namespace,
// which upstream keeps flat. `tags` re-exports those types grouped by the
// API tag whose operations reach them, so a type shared by several tags is
// still one Rust type. `manual` holds the hand-written wire behaviour that
// generated code cannot express, wired in through `x-rust-type` annotations.

#![allow(dead_code)]
// cargo-typify emits explicit Default implementations. Keep strict Clippy
// useful for hand-written code without modifying generated files.
#![allow(clippy::derivable_impls)]

pub mod manual;

pub mod components;
pub mod tags;
