// Generated by `scripts/typify_prep.py` + `cargo typify`.
// Do not edit by hand — re-run `scripts/regenerate-types.sh` after schema changes.
//
// Each submodule corresponds to one domain in docs/. Selected cross-domain
// types have a single owner module and are referenced from the other modules.

#![allow(dead_code)]
// cargo-typify emits explicit Default implementations. Keep strict Clippy
// useful for hand-written code without modifying generated files.
#![allow(clippy::derivable_impls)]

pub mod manual;

pub mod agent_portfolios;
pub mod feeds_posts;
pub mod identity;
pub mod market_data;
pub mod portfolio;
pub mod trading;
pub mod watchlists;
