// Generated by `scripts/typify_prep.py` + `cargo typify`.
// Do not edit by hand — re-run `scripts/regenerate-types.sh` after schema changes.
//
// Each submodule corresponds to one domain in docs/. Cross-domain types are
// duplicated across modules (e.g. `Market` appears in `market_data`, `trading`,
// and `feeds_posts`) so that each module is self-contained.

#![allow(dead_code)]

pub mod manual;

pub mod agent_portfolios;
pub mod feeds_posts;
pub mod identity;
pub mod market_data;
pub mod portfolio;
pub mod trading;
pub mod watchlists;
