// Generated by scripts/build_typify_input.py -- do not edit by hand.
//
// One module per eToro API tag, re-exporting the types that tag's
// operations reach. Every type is defined once in super::components;
// these are views onto it, so a type shared by several tags stays a
// single Rust type.

/// `Agent Portfolios`
pub mod agent_portfolios {
    pub use crate::types::components::AgentPortfolioApiCreateUserTokenResponse;
    pub use crate::types::components::AgentPortfolioApiErrorResponse;
    pub use crate::types::components::AgentPortfolioApiGetAllowedScopesResponse;
    pub use crate::types::components::AgentPortfolioItem;
    pub use crate::types::components::AgentPortfolioUserTokenItem;
    pub use crate::types::components::CreateAgentPortfolioPartialResponse;
    pub use crate::types::components::CreateAgentPortfolioV2Request;
    pub use crate::types::components::CreateAgentPortfolioV2Response;
    pub use crate::types::components::CreateAgentPortfolioV2UserTokenItem;
    pub use crate::types::components::CreateUserTokenV2Request;
    pub use crate::types::components::GetAgentPortfoliosResponse;
    pub use crate::types::components::ScopeNameItem;
    pub use crate::types::components::UpdateUserTokenV2Request;
}

/// `App Data`
pub mod app_data {
    pub use crate::types::components::BetaTestKeydataResponse;
}

/// `Balances`
pub mod balances {
    pub use crate::types::components::AccountBalanceData;
    pub use crate::types::components::BalanceAggregatorApiAccountType;
    pub use crate::types::components::BalanceAggregatorApiPublicErrorResponse;
    pub use crate::types::components::BalancesErrorResponse;
    pub use crate::types::components::EquityDetailsData;
    pub use crate::types::components::GetBalancesResponse;
    pub use crate::types::components::GetHistoricalBalancesResponse;
    pub use crate::types::components::HistoricalAccountData;
    pub use crate::types::components::HistoricalDailySnapshotData;
}

/// `Cash Accounts`
pub mod cash_accounts {
    pub use crate::types::components::BankIdentifierEntry;
    pub use crate::types::components::BankTransferDetails;
    pub use crate::types::components::CardTransactionDetails;
    pub use crate::types::components::CashAccountTransaction;
    pub use crate::types::components::CashAccountTransactionsResponse;
    pub use crate::types::components::Counterparty;
    pub use crate::types::components::FiatbackApiPublicErrorResponse;
    pub use crate::types::components::InternalTransferDetails;
    pub use crate::types::components::PaginationCursor;
}

/// `Clubs`
pub mod clubs {
    pub use crate::types::components::ClubDashboardDataResponse;
    pub use crate::types::components::ClubInfo;
    pub use crate::types::components::ClubOffer;
    pub use crate::types::components::ClubsApiAvatar;
    pub use crate::types::components::ClubsApiPublicErrorResponse;
    pub use crate::types::components::ContactInfo;
    pub use crate::types::components::ContactsResponse;
    pub use crate::types::components::DowngradeRiskResponse;
    pub use crate::types::components::OfferInBundle;
    pub use crate::types::components::StaticEligibleOffer;
    pub use crate::types::components::UserOffersData;
    pub use crate::types::components::Webinar;
    pub use crate::types::components::WebinarsResponse;
}

/// `Copy Trading`
pub mod copy_trading {
    pub use crate::types::components::CopyTradingCloseRequest;
    pub use crate::types::components::CopyTradingEligibilityRequest;
    pub use crate::types::components::CopyTradingEligibilityResponse;
    pub use crate::types::components::CopyTradingErrorResponse;
    pub use crate::types::components::CopyTradingRegisterRequest;
    pub use crate::types::components::CopyTradingStatusResponse;
    pub use crate::types::components::GatewayErrorResponse;
    pub use crate::types::components::TokenedResponse;
}

/// `Copy Trading - Demo`
pub mod copy_trading_demo {
    pub use crate::types::components::CopyTradingCloseRequest;
    pub use crate::types::components::CopyTradingEligibilityRequest;
    pub use crate::types::components::CopyTradingEligibilityResponse;
    pub use crate::types::components::CopyTradingErrorResponse;
    pub use crate::types::components::CopyTradingRegisterRequest;
    pub use crate::types::components::CopyTradingStatusResponse;
    pub use crate::types::components::GatewayErrorResponse;
    pub use crate::types::components::TokenedResponse;
}

/// `Identity`
pub mod identity {
    pub use crate::types::components::MeResponse;
}

/// `Market Data`
pub mod market_data {
    pub use crate::types::components::CandlesResponse;
    pub use crate::types::components::ClosingPricesResponse;
    pub use crate::types::components::ExchangesResponse;
    pub use crate::types::components::Instrument;
    pub use crate::types::components::InstrumentSearchResponse;
    pub use crate::types::components::InstrumentTypesResponse;
    pub use crate::types::components::InstrumentsResponse;
    pub use crate::types::components::LiveRatesResponse;
    pub use crate::types::components::StocksIndustriesResponse;
}

/// `Notifications`
pub mod notifications {
    pub use crate::types::components::InAppNotificationMessage;
    pub use crate::types::components::InAppNotificationsMetadata;
    pub use crate::types::components::InAppNotificationsResult;
}

/// `PI Data`
pub mod pi_data {
    pub use crate::types::components::GeCopiersResponse;
}

/// `PortfolioSearch`
pub mod portfolio_search {
    pub use crate::types::components::PortfolioSearchBffApiError;
    pub use crate::types::components::PortfolioSearchResponse;
    pub use crate::types::components::PortfolioSearchResult;
}

/// `Price Alerts`
pub mod price_alerts {
    pub use crate::types::components::CreatePriceAlertRequest;
    pub use crate::types::components::DeletePriceAlertResponse;
    pub use crate::types::components::PriceAlert;
    pub use crate::types::components::PriceAlertCollectionResponse;
    pub use crate::types::components::PriceAlertErrorResponse;
    pub use crate::types::components::PriceAlertMutationResponse;
    pub use crate::types::components::PriceAlertsApiPublicErrorResponse;
    pub use crate::types::components::UpdatePriceAlertRequest;
}

/// `Rankings`
pub mod rankings {
    pub use crate::types::components::CustomerRankingResponse;
    pub use crate::types::components::RankItem;
    pub use crate::types::components::RankingSummaryResponse;
    pub use crate::types::components::RankingTagsResponse;
    pub use crate::types::components::RankingsError;
    pub use crate::types::components::RankingsListResponse;
    pub use crate::types::components::RankingsMultipleResponse;
    pub use crate::types::components::RankingsMultipleResponseItem;
}

/// `SSO - Applications`
pub mod sso_applications {
    pub use crate::types::components::ApplicationItem;
    pub use crate::types::components::ApplicationScopeItem;
    pub use crate::types::components::CreateApplicationBody;
    pub use crate::types::components::CreateApplicationResponse;
    pub use crate::types::components::GetApplicationsResponse;
    pub use crate::types::components::RotateClientSecretResponse;
    pub use crate::types::components::ScopeItem;
    pub use crate::types::components::StsMetadataFrontApiErrorResponse;
    pub use crate::types::components::UpdateApplicationBody;
    pub use crate::types::components::UpdateApplicationResponse;
}

/// `SSO - Scopes`
pub mod sso_scopes {
    pub use crate::types::components::GetScopesResponse;
    pub use crate::types::components::ScopeResponseItem;
}

/// `Social Feeds`
pub mod social_feeds {
    pub use crate::types::components::Attachment;
    pub use crate::types::components::Attachments;
    pub use crate::types::components::Comment;
    pub use crate::types::components::CommentCreateRequest;
    pub use crate::types::components::CommentUpdateRequest;
    pub use crate::types::components::CommentsResponse;
    pub use crate::types::components::Discussion;
    pub use crate::types::components::DiscussionCreateRequest;
    pub use crate::types::components::DiscussionUpdateRequest;
    pub use crate::types::components::DiscussionsPost;
    pub use crate::types::components::DiscussionsResponse;
    pub use crate::types::components::Emotion;
    pub use crate::types::components::Market;
    pub use crate::types::components::PollCreateRequest;
    pub use crate::types::components::Post;
    pub use crate::types::components::SharePostRequest;
    pub use crate::types::components::SharesResponse;
    pub use crate::types::components::User;
}

/// `Sub-Accounts - eToro Trading`
pub mod sub_accounts_etoro_trading {
    pub use crate::types::components::CreateSubAccountUserTokenRequest;
    pub use crate::types::components::EtoroTradingSubAccountsMoneyTransferRequest;
    pub use crate::types::components::EtoroTradingSubAccountsOperationsApiCreateUserTokenResponse;
    pub use crate::types::components::EtoroTradingSubAccountsOperationsApiErrorResponse;
    pub use crate::types::components::EtoroTradingSubAccountsOperationsApiGetAllowedScopesResponse;
    pub use crate::types::components::ListUserTokensResponse;
    pub use crate::types::components::ScopeNameItem;
    pub use crate::types::components::UpdateSubAccountUserTokenRequest;
    pub use crate::types::components::UserTokenItem;
}

/// `Trading - Demo`
pub mod trading_demo {
    pub use crate::types::components::AggregatedPortfolioAccountTotals;
    pub use crate::types::components::CancelOrderResponse;
    pub use crate::types::components::ClientPortfolio;
    pub use crate::types::components::CostBreakdown;
    pub use crate::types::components::GetCostResponse;
    pub use crate::types::components::GetOrderInfoAsset;
    pub use crate::types::components::GetOrderInfoOpeningData;
    pub use crate::types::components::GetOrderInfoPositionExecution;
    pub use crate::types::components::GetOrderInfoResponse;
    pub use crate::types::components::GetOrderInfoStatus;
    pub use crate::types::components::InstrumentBreakdownAssetDemo;
    pub use crate::types::components::InstrumentBreakdownClosePositionDetailDemo;
    pub use crate::types::components::InstrumentBreakdownInstrumentDemo;
    pub use crate::types::components::InstrumentBreakdownMirrorDemo;
    pub use crate::types::components::InstrumentBreakdownOrderDemo;
    pub use crate::types::components::InstrumentBreakdownPositionDemo;
    pub use crate::types::components::InstrumentBreakdownResponseDemo;
    pub use crate::types::components::InstrumentEligibility;
    pub use crate::types::components::InstrumentEligibilityRequest;
    pub use crate::types::components::InstrumentEligibilityResponse;
    pub use crate::types::components::LeverageConfiguration;
    pub use crate::types::components::Mirror;
    pub use crate::types::components::OrderForClose;
    pub use crate::types::components::OrderForCloseInfoResponse;
    pub use crate::types::components::OrderForCloseMultiple;
    pub use crate::types::components::OrderForClosePositionInfoResponse;
    pub use crate::types::components::OrderForOpen;
    pub use crate::types::components::PortfolioResponse;
    pub use crate::types::components::PortfolioResponseWithPnl;
    pub use crate::types::components::ProblemDetails;
    pub use crate::types::components::TradingDemoAdminApiUnifiedOrderRequest;
    pub use crate::types::components::TradingDemoApiPosition;
    pub use crate::types::components::TradingPortfolioDemoApiAggregatedPortfolioInstrumentAggregate;
    pub use crate::types::components::TradingPortfolioDemoApiAggregatedPortfolioMirrorAggregate;
    pub use crate::types::components::TradingPortfolioDemoApiAggregatedPortfolioMirrorTotals;
    pub use crate::types::components::TradingPortfolioDemoApiAggregatedPortfolioResponse;
    pub use crate::types::components::TradingRealAdminApiOrder;
    pub use crate::types::components::TradingRealAdminApiPosition;
    pub use crate::types::components::UnifiedOrderResponse;
    pub use crate::types::components::UpdatePositionRequest;
    pub use crate::types::components::UpdatePositionResponse;
}

/// `Trading - Real`
pub mod trading_real {
    pub use crate::types::components::AggregatedPortfolioAccountTotals;
    pub use crate::types::components::CancelOrderResponse;
    pub use crate::types::components::ClientPortfolio;
    pub use crate::types::components::CostBreakdown;
    pub use crate::types::components::GetCostResponse;
    pub use crate::types::components::GetOrderInfoAsset;
    pub use crate::types::components::GetOrderInfoOpeningData;
    pub use crate::types::components::GetOrderInfoPositionExecution;
    pub use crate::types::components::GetOrderInfoResponse;
    pub use crate::types::components::GetOrderInfoStatus;
    pub use crate::types::components::InstrumentBreakdownAsset;
    pub use crate::types::components::InstrumentBreakdownClosePositionDetail;
    pub use crate::types::components::InstrumentBreakdownInstrument;
    pub use crate::types::components::InstrumentBreakdownMirror;
    pub use crate::types::components::InstrumentBreakdownOrder;
    pub use crate::types::components::InstrumentBreakdownPosition;
    pub use crate::types::components::InstrumentBreakdownResponse;
    pub use crate::types::components::InstrumentEligibility;
    pub use crate::types::components::InstrumentEligibilityRequest;
    pub use crate::types::components::InstrumentEligibilityResponse;
    pub use crate::types::components::LeverageConfiguration;
    pub use crate::types::components::Mirror;
    pub use crate::types::components::OrderForClose;
    pub use crate::types::components::OrderForCloseInfoResponse;
    pub use crate::types::components::OrderForCloseMultiple;
    pub use crate::types::components::OrderForClosePositionInfoResponse;
    pub use crate::types::components::OrderForOpen;
    pub use crate::types::components::PortfolioResponse;
    pub use crate::types::components::PortfolioResponseWithPnl;
    pub use crate::types::components::ProblemDetails;
    pub use crate::types::components::TradingDemoApiPosition;
    pub use crate::types::components::TradingPortfolioRealApiAggregatedPortfolioInstrumentAggregate;
    pub use crate::types::components::TradingPortfolioRealApiAggregatedPortfolioMirrorAggregate;
    pub use crate::types::components::TradingPortfolioRealApiAggregatedPortfolioMirrorTotals;
    pub use crate::types::components::TradingPortfolioRealApiAggregatedPortfolioResponse;
    pub use crate::types::components::TradingRealAdminApiOrder;
    pub use crate::types::components::TradingRealAdminApiPosition;
    pub use crate::types::components::TradingRealAdminApiUnifiedOrderRequest;
    pub use crate::types::components::UnifiedOrderResponse;
    pub use crate::types::components::UpdatePositionRequest;
    pub use crate::types::components::UpdatePositionResponse;
}

/// `Transfer`
pub mod transfer {
    pub use crate::types::components::LookupAccountIdentifier;
    pub use crate::types::components::LookupAccountType;
    pub use crate::types::components::MoneyTransferRequest;
    pub use crate::types::components::MoneyTransferResponse;
    pub use crate::types::components::MoneybusApiAccountType;
    pub use crate::types::components::TransferAccountRef;
    pub use crate::types::components::TransferLookupDestination;
    pub use crate::types::components::TransferLookupResponse;
    pub use crate::types::components::TransferLookupResult;
    pub use crate::types::components::TransferLookupSource;
    pub use crate::types::components::TransferableBalanceResponse;
}

/// `User Stats`
pub mod user_stats {
    pub use crate::types::components::AssetsHistoryAsset;
    pub use crate::types::components::AssetsHistoryEntry;
    pub use crate::types::components::AssetsHistoryResponse;
    pub use crate::types::components::CopiersCurrentResponse;
    pub use crate::types::components::ExposureHistoryEntry;
    pub use crate::types::components::ExposureHistoryResponse;
    pub use crate::types::components::ExposureItem;
    pub use crate::types::components::GainHistoryResponse;
    pub use crate::types::components::GainPoint;
    pub use crate::types::components::StandardErrorResponse;
    pub use crate::types::components::StatsAssetsApiError;
    pub use crate::types::components::StatsExposureApiError;
    pub use crate::types::components::StatsGainApiError;
}

/// `Users Info`
pub mod users_info {
    pub use crate::types::components::GainEntry;
    pub use crate::types::components::GetUserDailyGainResponse;
    pub use crate::types::components::GetUserGainResponse;
    pub use crate::types::components::PublicAggregatedInfoResponse;
    pub use crate::types::components::PublicAggregatedInfoUiUserAvatar;
    pub use crate::types::components::PublicAggregatedInfoUiUserBio;
    pub use crate::types::components::PublicAggregatedInfoUser;
    pub use crate::types::manual::PublicAggregatedInfoAccountStatus;
    pub use crate::types::manual::PublicAggregatedInfoPlayerStatus;
    pub use crate::types::manual::PublicAggregatedInfoPlayerStatusReason;
}

/// `Watchlists`
pub mod watchlists {
    pub use crate::types::components::BffFacadeRequest;
    pub use crate::types::components::CandlePoint;
    pub use crate::types::components::CuratedList;
    pub use crate::types::components::CuratedListItem;
    pub use crate::types::components::CuratedListsResponse;
    pub use crate::types::components::InstrumentMarketData;
    pub use crate::types::components::InstrumentMetadataSlim;
    pub use crate::types::components::LeverageConfig;
    pub use crate::types::components::MarketEnrichData;
    pub use crate::types::components::MarketRecommendationsResponse;
    pub use crate::types::components::SiblingData;
    pub use crate::types::components::SmartPortfolioEnrichData;
    pub use crate::types::components::SvgAvatar;
    pub use crate::types::components::TradeButtonStatusData;
    pub use crate::types::components::TradingAdditionalData;
    pub use crate::types::components::UserEnrichData;
    pub use crate::types::components::WatchlistApiAvatar;
    pub use crate::types::components::WatchlistComponentResponse;
    pub use crate::types::components::WatchlistItemDto;
    pub use crate::types::components::WatchlistResponse;
    pub use crate::types::components::WatchlistsResponse;
}
